### ISSUE TITLE
Support CSV + dicts in FEMap

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/cinnabar#33]
Right now we only support reading in a CSV, but we should expose the API to allow users to pass in python objects.

https://github.com/openforcefield/openff-arsenic/blob/master/openff/arsenic/wrangle.py#L67

To avoid major refactoring and to keep things backwards compatible, I'll add a bit of code that checks if `csv` is a file or a python object, and then take it from there.

**Comment by glass-w** [comment]
More generally we should standardise on a CSV format that should be read in. Right now the `read_csv` function just [checks if some keywords are in a line](https://github.com/openforcefield/openff-arsenic/blob/9d87d7631ca4408895dc95e54ab135e7946a344d/openff/arsenic/wrangle.py#L17-L21). Perhaps we could move to a YAML input instead?

**Comment by mikemhenry** [comment]
We should have some standard format, but I think that we should support reading in a file + also working directly with the library so that we don't have to have a step where we write our results to a file. I'll actually need to take a look at what the CSV ends up looking like to see if a different file format could be better! But it is always nice to be able to just pass in some object(s) and skip writing to disk if it isn't needed.

**Comment by richardjgowers** [comment]
I think we can (& should) break things if we want, that's the point of 0.x.  I think an initialisation closely following what `networkx` allows is probably best, with a `from_csv` classmethod as a way to/from a file version.
