### ISSUE TITLE
refactoring bootstrap stats

### ISSUE THREAD

**Issue by RiesBen** [OpenFreeEnergy/cinnabar#99]
https://github.com/OpenFreeEnergy/cinnabar/blob/d96573e2b4cde36e2b20a1812fd5802d80ef4164/cinnabar/stats.py#L117

it might make sense to replace the manual bootstrap implementation with scipy bootstrap to make code clearer and leaner, example:
```
from scipy import stats

dE = y_exp - y_pred

rmse = lambda x: np.sqrt(np.mean(np.square(x)))
rmse_res = rmse(dE)
rmse_res_err = stats.bootstrap(dE, rmse).standard_error
 
 ```

**Comment by RiesBen** [comment]
These line looks like a problem to me, for the uncertainty sampling in the bootstrapping.
The random picking of one, is only adding additional noise, not as expected more certainty of the given mean???

https://github.com/OpenFreeEnergy/cinnabar/blob/d96573e2b4cde36e2b20a1812fd5802d80ef4164/cinnabar/stats.py#L125

**Comment by IAlibay** [comment]
I'm not sure I understand your point fully here @RiesBen - that line should be aiming to add a random noise along the error bar so that your sample accounts for it?
